### ISSUE TITLE
The game wont let me leave.

### ISSUE THREAD

**Issue by catboy6969** [draumaz/butterfly#3]
My wife left me. And the game wont close. Seperate issue.

**Comment by draumaz** [comment]
Have you listed?

**Comment by catboy6969** [comment]
I listed the world and yet found that we are not written there.

**Comment by draumaz** [comment]
> purrhaps

Are you using [kitty](https://github.com/kovidgoyal/kitty)?

**Comment by catboy6969** [comment]
and yet you are dead

**Comment by draumaz** [comment]
Thank you for your input.
